# Generated by Django 3.2 on 2022-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myt',
            fields=[
                ('character', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
