# Generated by Django 3.2 on 2022-02-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myt',
            name='account',
            field=models.IntegerField(),
        ),
    ]
