# Generated by Django 3.2 on 2022-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0002_alter_myt_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
