# Generated by Django 3.2 on 2022-02-22 03:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0004_auto_20220221_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='MytCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('legion', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
                ('times', jsonfield.fields.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myts', models.ManyToManyField(to='myt.Myt')),
            ],
        ),
    ]
