# Generated by Django 3.2 on 2022-02-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0005_mytcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytcard',
            name='myts',
            field=models.ManyToManyField(blank=True, to='myt.Myt'),
        ),
    ]
