# Generated by Django 3.2 on 2022-03-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0006_alter_mytcard_myts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytcard',
            name='name',
        ),
    ]
