# Generated by Django 3.2 on 2022-03-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0008_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='myt',
            name='rooms',
            field=models.ManyToManyField(to='myt.Room'),
        ),
        migrations.AddField(
            model_name='mytcard',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myt.room'),
            preserve_default=False,
        ),
    ]
