# Generated by Django 3.2 on 2022-10-14 13:24

from django.db import migrations, models


def fix_custom_legion_and_message_of_myt_cards(apps, schema_editor):
    MytCard = apps.get_model('myt', 'MytCard')
    legions = ['kakul-saydon', 'akkan', 'thaemine', 'brelshaza', 'vykas', 'valtan', 'custom']

    for myt_card in MytCard.objects.all():
        if myt_card.legion not in legions:
            myt_card.message = myt_card.legion
            myt_card.legion = 'custom'
            myt_card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myt', '0015_mytcard_message'),
    ]

    operations = [
        migrations.RunPython(fix_custom_legion_and_message_of_myt_cards),
    ]